# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 09:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toolsscript',
            name='tool_run_type',
            field=models.IntegerField(choices=[(0, 'SaltState'), (1, 'Shell'), (4, 'Salt命令')], default=0, verbose_name='脚本类型'),
        ),
    ]
